### PR TITLE
Play with sequence - Separate SNO conversion from infra remove

### PR DESCRIPTION
**Pull request by cuppett**
There's a fix really needed in 3dfe56b0982920a88d2236cbe808c3c3fd40af83, but the subsequent commits aren't fully proven yet.

### CODE REVIEW

**Comment by cuppett** [comment]
I think in my last attempt here, I caught a cert rotation or something with bad timing and the wheels came off my bus. 

Letting a new attempt sit for an hour or so after the install before performing spot conversion. I vaguely remember this from our service delivery discussions around hibernation in managed clusters. If that works, we may need to put a note in the README.

**Comment by eformat** [comment]
hmm .. yeah you could also check csr are approved (they should be !) but i did have one instance where they needed manual prodding .. not sure why ...

```
oc get csr -o name | xargs oc adm certificate approve
```

**Comment by cuppett** [comment]
That was important. I needed that. Got stuck there again and the CSR approve thing fixed it right up. Should we add that to fix-instance-id.sh?

Another thing, I've had more success with oc by doing KUBECONFIG= than by doing oc login to the API server with password. Should we do that as well?

**Comment by eformat** [comment]
csr's - ah good, yes i can add in as a step!

KUBECONFIG= ... interesting .. for me, if not set .. it just uses ~/.kube/config as the default .. i wonder why that is causing you an issue ...

i have had issues when my ~/.kube/config is SOOO large / long .. that it causes problems .. after you login to so many clusters .. maybe move it aside ? see if that work better

**Comment by cuppett** [comment]
I've got it in my branch. Getting ready to push something. 

On the KUBECONFIG, I think it's more about what is your current/default context.

**Comment by eformat** [comment]
ok .. i just pushed this for csr approval

https://github.com/eformat/sno-for-100/commit/387ee6ea0fc91b838a06f5ff110b349ab072a56c

**Comment by cuppett** [comment]
I have a bit of a different sequence here that streamlines a bit. Give this a check? wdyt?

Here's how it looks:
```
 -> restart_instance starting [ i-0c085ed6f004a426a ] OK
Waiting for 200 response from openshift api https://api.sno-2.openshiftcorp.com:6443/healthz.
error: You must be logged in to the server (Unauthorized)
Waiting for 0 rc from oc commands.
error: You must be logged in to the server (Unauthorized)
Waiting for 0 rc from oc commands.
error: You must be logged in to the server (Unauthorized)
Waiting for 0 rc from oc commands.
error: You must be logged in to the server (Unauthorized)
Waiting for 0 rc from oc commands.
error: You must be logged in to the server (Unauthorized)
Waiting for 0 rc from oc commands.
error: You must be logged in to the server (Unauthorized)
Waiting for 0 rc from oc commands.
error: You must be logged in to the server (Unauthorized)
Waiting for 0 rc from oc commands.
error: You must be logged in to the server (Unauthorized)
Waiting for 0 rc from oc commands.
NAME        AGE    SIGNERNAME                      REQUESTOR                                                REQUESTEDDURATION   CONDITION
csr-4jmwd   147m   kubernetes.io/kubelet-serving   system:node:ip-10-0-152-160.us-east-2.compute.internal   <none>              Approved,Issued
csr-jn55n   132m   kubernetes.io/kubelet-serving   system:node:ip-10-0-152-160.us-east-2.compute.internal   <none>              Approved,Issued
csr-jrxmn   102m   kubernetes.io/kubelet-serving   system:node:ip-10-0-152-160.us-east-2.compute.internal   <none>              Approved,Issued
csr-q6zgj   117m   kubernetes.io/kubelet-serving   system:node:ip-10-0-152-160.us-east-2.compute.internal   <none>              Approved,Issued
csr-qhtbg   87m    kubernetes.io/kubelet-serving   system:node:ip-10-0-152-160.us-east-2.compute.internal   <none>              Approved,Issued
csr-r286l   153m   kubernetes.io/kubelet-serving   system:node:ip-10-0-152-160.us-east-2.compute.internal   <none>              Approved,Issued
csr-vrvsb   53m    kubernetes.io/kubelet-serving   system:node:ip-10-0-152-160.us-east-2.compute.internal   <none>              Approved,Issued
certificatesigningrequest.certificates.k8s.io/csr-4jmwd approved
certificatesigningrequest.certificates.k8s.io/csr-jn55n approved
certificatesigningrequest.certificates.k8s.io/csr-jrxmn approved
certificatesigningrequest.certificates.k8s.io/csr-q6zgj approved
certificatesigningrequest.certificates.k8s.io/csr-qhtbg approved
certificatesigningrequest.certificates.k8s.io/csr-r286l approved
certificatesigningrequest.certificates.k8s.io/csr-vrvsb approved
```

The last thing I was thinking about was calling "reboot-instances" instead of stop/start in the fix-instance-id.sh script as a bit of an optimization and not chance the wrestle of stop/start with the spot reservation logic. (I think AWS is starting us as well if we had a pause there since they have capacity and a persistent request; reboot is cleaner in that regard.)

But, I'm done for this weekend until Monday. Driving back home tomorrow so will be offline.

**Comment by cuppett** [comment]
Major changes in here:

1. Revisited conversion of spot after initial infrastructure changes (with appropriate moves between the two scripts)
2. Added documentation and pointers to the README.md for other capabilities and to match changes above
3. Using KUBECONFIG instead of KUBEADMIN_PASSWORD to allow OIDC changes and removal of htpasswd
4. Approving CSRs where that got stuck on a couple runs between us

**Comment by eformat** [comment]
Rogga .. let me run these thru from scratch as a test ...

**Comment by eformat** [comment]
👍 worked like a charm ! LGTM

**Pull request merged**
